POST http://localhost:3003/api/locations
Content-Type: application/json

{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": {
        "longitude": "41.8261716", 
        "latitude": "-71.4073375"
    }
  },
  "properties": {
    "title": "Brown University",
    "description": "First Aid",
    "type": "firstAid"
  }
}