POST http://localhost:3003/api/locations
Content-Type: application/json

{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": {
        "latitude": "13.404954", 
        "longitude": "52.520008"
    }
  }
}